### ISSUE TITLE
Controlling the reconnection-timeout

### ISSUE THREAD

**Issue by willdurand** [igorw/EventSource#2]
Hi,

What about adding a support for the `retry:` line to define the timeout value ?
See http://www.html5rocks.com/en/tutorials/eventsource/basics/#toc-reconnection-timeout

That way we could avoid the infinite loop + `sleep()` :)

William

**Comment by igorw** [comment]
I have added support to specify it. But I would like to note that this is absolutely not recommended. The whole point of EventSource is that you can maintain a persistent connection and reduce latency. If you don't take advantage of that, you might as well be using AJAX polling. ;-)

EDIT: Note that you don't have to use while+sleep, there are other use cases / methods.

**Comment by willdurand** [comment]
That makes sense indeed. But, I didnt it was not recommended at all :/
